# Generated by Django 5.2.7 on 2025-11-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('true_false', 'True/False'), ('text', 'Text')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='student_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
