# Generated by Django 5.2.7 on 2025-11-04 00:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('mnc', 'MNC (Multinational Corporation)'), ('startup', 'Startup'), ('core', 'Core Company'), ('service', 'Service Based'), ('product', 'Product Based')], max_length=20)),
                ('package_min', models.FloatField(help_text='Minimum package in LPA')),
                ('package_max', models.FloatField(help_text='Maximum package in LPA')),
                ('min_cgpa', models.FloatField(default=6.0)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('required_branches', models.CharField(help_text='Comma-separated branch codes', max_length=500)),
                ('technical_skills_min', models.FloatField(default=5.0)),
                ('communication_skills_min', models.FloatField(default=5.0)),
                ('aptitude_score_min', models.FloatField(default=50.0)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_visited', models.DateField(blank=True, null=True)),
                ('total_placements', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('avg_cgpa', models.FloatField(default=0.0)),
                ('avg_employability', models.FloatField(default=0.0)),
                ('placement_ready_count', models.IntegerField(default=0)),
                ('avg_communication', models.FloatField(default=0.0)),
                ('avg_technical', models.FloatField(default=0.0)),
                ('avg_coding', models.FloatField(default=0.0)),
                ('avg_aptitude', models.FloatField(default=0.0)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('branch', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='EmployabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_score', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('technical_score', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('aptitude_score', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coding_score', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('soft_skills_score', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('projects_count', models.IntegerField(default=0)),
                ('internships_count', models.IntegerField(default=0)),
                ('certifications_count', models.IntegerField(default=0)),
                ('hackathons_count', models.IntegerField(default=0)),
                ('overall_employability', models.FloatField(default=0.0)),
                ('placement_readiness', models.CharField(choices=[('excellent', 'Excellent (90-100%)'), ('good', 'Good (70-89%)'), ('average', 'Average (50-69%)'), ('needs_improvement', 'Needs Improvement (<50%)')], default='average', max_length=20)),
                ('skill_gaps', models.TextField(blank=True, help_text='Areas that need improvement')),
                ('last_assessed', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recommended_companies', models.ManyToManyField(blank=True, related_name='suitable_students', to='predictor.company')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employability', to='predictor.studentrecord')),
            ],
            options={
                'ordering': ['-overall_employability'],
            },
        ),
    ]
