# Generated by Django 5.2.7 on 2025-11-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_company_departmentanalytics_employabilityscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='cgpa_manually_entered',
            field=models.BooleanField(default=False, help_text='True if CGPA was entered directly, not calculated'),
        ),
    ]
