# Generated by Django 5.2.7 on 2025-11-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_studentrecord_cgpa_manually_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='reference_text',
            field=models.TextField(blank=True),
        ),
    ]
